"""
This script receives as input a project_dir that contains a specific config.yml file.
It initializes a model with the parameters specified in the config.yml file.
It fits the model with data from sleap experiments that are read and initialized as
per usual while fitting any model with experiments.
In the case of the hyperparameter sweep, the experiments are split in train-test splits.
For now, there are 5 experiments that I am fitting the models on.
I will take four of these experiments to train the model on and evaluate the model on the
fifth experiment.

The script is launched on Della using a SLURM array job that iterates over the array_args.txt
file that is generated by generate_hyperparams_configs.py. The array_args.txt file contains
a list of project_dirs.
"""

import numpy as np
from keypoint_moseq.project.fit_utils import find_sleap_paths, load_data_from_expts, run_fit_PCA, fit_keypoint_ARHMM, \
    resume_slds_fitting_to_new_data
from keypoint_moseq.run.hyperparams.get_test_probs import get_test_probs

import argparse
from rich.pretty import pprint
from sklearn.model_selection import KFold


def create_cli_parser():
    """Create an argument parser for the command line interface."""
    parser = argparse.ArgumentParser(
        description="Sweep hyperparameters for ARHMM and SLDS models on SLEAP data."
    )
    parser.add_argument(
        "-p",
        "--project_dir",
        type=str,
        required=True,
        help="Path to project directory containing config.yml file.",
    )
    parser.add_argument(
        "-v",
        "--video_dir",
        type=str,
        required=True,
        help="Path to video directory containing sleap experiments.",
    )
    parser.add_argument('--use_instance', type=int, default=1)

    return parser


def sample_paths_for_initialization(sleap_paths):
    # TODO: sample randomly
    init_paths = sleap_paths[:5]
    return init_paths


def train(train_paths, project_dir, use_instance):
    # TODO (US): return logll of training iters

    init_paths = sample_paths_for_initialization(train_paths)

    # Load train data from train experiment folders
    data, batch_info = load_data_from_expts(init_paths, project_dir, use_instance)

    # Fit PCA
    run_fit_PCA(data, project_dir)

    # Initialize and fit ARHMM
    _, _, checkpoint_path = fit_keypoint_ARHMM(project_dir, data, batch_info)

    # Fit SLDS
    resume_slds_fitting_to_new_data(checkpoint_path, project_dir, train_paths)

    return checkpoint_path


def fitCV(sleap_paths, project_dir, use_instance):
    """

    Parameters
    ----------
    sleap_paths
    project_dir

    Returns
    -------

    """
    sleap_paths = np.array(sleap_paths)

    log_joint = []
    log_y_given_model = []

    kfold = KFold(n_splits=np.min([5, len(sleap_paths)]))
    for tr, te in kfold.split(sleap_paths):
        print("tr", tr, "te", te)
        train_paths, test_paths = sleap_paths[tr], sleap_paths[te]
        print("train_paths", train_paths)
        print("test_paths", test_paths)

        model_name = train(train_paths, project_dir, use_instance)
        log_y_and_model, log_ll = get_test_probs(test_paths, project_dir, model_name)
        log_joint.append(log_y_and_model)
        log_y_given_model.append(log_ll)

        print("LLs for tr:", tr, "te:", te, "log y,model", log_y_given_model, "log y|model", log_y_given_model)

    return log_joint, log_y_given_model


def plot_ll(log_joint, log_data_ll):
    print("log_joint", log_joint)
    print("log_data_ll", log_data_ll)
    return


def main():
    # Main control flow of the experiment
    # Parse CL args
    parser = create_cli_parser()
    args = parser.parse_args()
    print("Args:")
    pprint(vars(args))
    print()
    video_dir = args.video_dir
    project_dir = args.project_dir
    use_instance = args.use_instance

    # Get sleap experiment folders 
    sleap_paths = find_sleap_paths(video_dir)
    print("sleap_paths", sleap_paths)
    sleap_paths = np.array(sleap_paths)
    log_joint, log_data_ll = fitCV(sleap_paths, project_dir, use_instance)
    plot_ll(log_joint, log_data_ll)


if __name__ == "__main__":
    main()
