"""
This script takes a keypoint_moseq model parameters and some
observed data and computes the log probability of the data.

It saves the model parameters and the log probability of the data 
in a .csv file for downstream analysis with pandas and seaborn. 

This .csv file is saved in the same location as the array_args.txt
file that is generated by generate_hyperparams_configs.py.

Given a (list of) project_dir that contain within them other directories
with a results.h5 file, read the results.h5 file and unload the model
parameters from the results.h5, find the model likelihood of the data
and 

"""

from jax_moseq.models import keypoint_slds
import keypoint_moseq as kpm
from keypoint_moseq.run.fit_kpms_to_sleap import find_sleap_paths
import os
import argparse
from rich.pretty import pprint
import joblib

def create_cli_parser():
    """Create an argument parser for the command line interface."""
    parser = argparse.ArgumentParser()

    parser.add_argument(
    "-p",
    "--project_dir",
    type=str,
    required=True,
    help="Path to project directory containing model checkpoint file.",
    )

    parser.add_argument(
    "-v",
    "--video_dir",
    type=str,
    required=True,
    help="Path to video directory containing data for which to compute model log likelihood.",
    )

    return parser


def find_checkpoint(project_dir):
    
    """
    Recursively search within a directory for checkpoint.p files

    Parameters
    ----------
    project_dirs : list
        A list containing paths to directories containing checkpoint.p files
    """

    for root, dirs, files in os.walk(project_dir):
        for file in files:
            if file == "checkpoint.p":
                return os.path.join(root, file)

    return None



def get_model_llh(project_dir, coordinates, confidences=None):
    """
    Unpack the model parameters from the checkpoint_paths
    and compute the log likelihood of the data

    Parameters
    ----------
    checkpoint_paths : list
        A list of paths to checkpoint.p files
    coordinates: dict

    confidences: None

    """
    # Load config
    config = kpm.load_config(project_dir)
    
    # Find checkpoint
    checkpoint_path = find_checkpoint(project_dir)
    if checkpoint_path is not None:
        checkpoint = kpm.load_checkpoint(path=checkpoint_path)
    else:
        print(f"Checkpoint doesn't exist in {project_dir}")
        return
    
    # Resample model with test data
    model, data = kpm.apply_model(coordinates=coordinates, confidences=confidences, 
                        project_dir=project_dir, **checkpoint, **config,
                        plot_every_n_iters=0, use_saved_states=False,
                        pca=kpm.load_pca(project_dir),
                        num_iters=1,
                        return_model_only=True)

    # Compute model log likelihood
    llh = keypoint_slds.model_likelihood(data, **model)

    # Save LLHs to the same folder that contains the checkpoint
    dirname = os.path.dirname(checkpoint_path)
    save_path = os.path.join(dirname, 'llh.p')
    joblib.dump(llh, save_path)

    return llh


if __name__ == "__main__":
    parser = create_cli_parser()
    args = parser.parse_args()
    print("Args:")
    pprint(vars(args))

    project_dir = args.project_dir
    video_dir = args.video_dir

    # Load test data from test experiment folders
    test_paths = find_sleap_paths(video_dir)
    # Load test data from test experiment folders
    coordinates = kpm.load_keypoints_from_slp_list(test_paths)
    confidences = None

    llh = get_model_llh(project_dir, coordinates)
    print(llh)


    